import { NodeCollapseOutlined, ReloadOutlined } from "@ant-design/icons";
import { Button, Col, PageHeader, Row, Statistic, Card } from "antd";
import React from "react";
import { IData } from "../../model/data.model";
import StatisticDate from "../shared/StatisticDate";
import StatisticErrorIndex from "../shared/StatisticErrorIndex";

interface ICurrentStatusHeader {
  data: IData;
  toggleCollapse?: () => void;
  activePanels?: string[];
  loading: boolean;
  reload: () => void;
  latestLoad: Date;
}
export const CurrentStatusHeader: React.FC<ICurrentStatusHeader> = props => {
  const staticStyle = { fontSize: 20 };

  return (
    <Card style={{ margin: 24, marginTop: 10 }}>
      <PageHeader
        title="Project Status"
        subTitle="List of pull requests"
        style={{ padding: 0 }}
        extra={[
          <Button
            key="reload"
            type="primary"
            icon={<ReloadOutlined />}
            loading={props.loading}
            onClick={props.reload}
          >
            Reload
          </Button>
        ]}
      >
        <Row gutter={16}>
          <Col>
            <Statistic
              title="Generated By"
              value="Local Execution"
              valueStyle={staticStyle}
            />
          </Col>
          <Col>
            <Statistic
              title="Number of Projects"
              prefix={<NodeCollapseOutlined />}
              value={props.data.data.length}
              valueStyle={staticStyle}
            />
          </Col>
          <Col>
            <StatisticErrorIndex
              pullRequests={props.data.data.flatMap(
                project => project.pullRequests
              )}
            />
          </Col>
          <Col>
            <StatisticDate
              date={
                props.data?.metadata?.date
                  ? new Date(Date.parse(props.data?.metadata?.date))
                  : new Date()
              }
              text="Creation Date"
              intervalSeconds={1}
            />
          </Col>
          <Col>
            <StatisticDate
              date={props.latestLoad}
              text="Latest Load"
              intervalSeconds={1}
            />
          </Col>
        </Row>
      </PageHeader>
    </Card>
  );
};

export default CurrentStatusHeader;
