import {
  InfoCircleOutlined,
  LinkOutlined,
  NodeCollapseOutlined,
  ReloadOutlined,
  PullRequestOutlined
} from "@ant-design/icons";
import {
  Button,
  Card,
  Col,
  Modal,
  PageHeader,
  Popover,
  Row,
  Skeleton,
  Statistic,
  Tooltip,
  Typography
} from "antd";
import React, { Suspense, useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { IRootState } from "../../service";
import { STATISTICS_STYLE } from "../../shared/constants";
import Loading from "../shared/Loading";
import StatisticDate from "../shared/StatisticDate";
import StatisticErrorIndex from "../shared/StatisticErrorIndex";
import * as dataService from "../../service/data.service";

const ProjectStatusInformation = React.lazy(
  () => import("../shared/ProjectStatusInformation")
);
const StatisticPullRequests = React.lazy(
  () => import("../shared/StatisticPullRequests")
);
const StatisticErrorIndexByProject = React.lazy(
  () => import("../shared/StatisticErrorIndexByProject")
);

interface ICurrentStatusHeader {}
export const CurrentStatusHeader: React.FC<ICurrentStatusHeader> = props => {
  const dispatch = useDispatch();
  const data = useSelector((store: IRootState) => store.data.data);
  const loading = useSelector((store: IRootState) => store.data.loading);
  const [latestLoad, setLatestLoad] = useState<Date>(new Date());

  const getData = () => {
    dispatch(dataService.loadData());
  };

  useEffect(() => {
    if (data?.projects) {
      setLatestLoad(new Date());
    }
  }, [data]);

  const infoModal = () =>
    Modal.info({
      content: (
        <Suspense fallback={<Skeleton />}>
          <ProjectStatusInformation />
        </Suspense>
      ),
      onOk() {},
      width: 1000,
      centered: true
    });
  return (
    <Card style={{ margin: 24, marginTop: 10 }}>
      <PageHeader
        title={
          data.metadata?.title ? (
            <Typography.Title level={2}>
              {data.metadata?.title}
            </Typography.Title>
          ) : (
            <Skeleton.Input style={{ width: 200 }} />
          )
        }
        subTitle={
          data.metadata?.subtitle ?? <Skeleton.Input style={{ width: 400 }} />
        }
        style={{ padding: 0 }}
        extra={[
          <Tooltip key="reaload" title="Reload information from service">
            <Button
              key="reload"
              type="primary"
              icon={<ReloadOutlined />}
              loading={loading}
              onClick={getData}
            >
              Reload
            </Button>
          </Tooltip>,
          <Tooltip key="info" title="Show project status information">
            <Button
              key="info"
              type="text"
              shape="circle"
              icon={<InfoCircleOutlined />}
              onClick={infoModal}
            />
          </Tooltip>
        ]}
      >
        <Row gutter={16}>
          <Col>
            <Statistic
              title="Generated By"
              value={data.metadata?.createdBy}
              valueStyle={STATISTICS_STYLE}
              suffix={
                data.metadata?.createdUrl ? (
                  <Tooltip title="Visit job generating the report">
                    <Button
                      type="link"
                      href={data.metadata?.createdUrl}
                      target="_blank"
                      icon={<LinkOutlined />}
                      style={{
                        padding: 0,
                        ...STATISTICS_STYLE,
                        fontWeight: "bold"
                      }}
                    />
                  </Tooltip>
                ) : null
              }
            />
          </Col>
          <Col>
            <Popover
              content={
                <Suspense fallback={<Loading />}>
                  <StatisticPullRequests projects={data.projects} size={12} />
                </Suspense>
              }
              placement="bottom"
            >
              <Statistic
                title="Number of Projects"
                prefix={<NodeCollapseOutlined />}
                value={data.projects.length}
                valueStyle={{ ...STATISTICS_STYLE, fontWeight: "bold" }}
              />
            </Popover>
          </Col>
          <Col>
            <Statistic
              title="Number of Pull Requests"
              prefix={<PullRequestOutlined />}
              value={data.projects.flatMap(p => p.pullRequests).length}
              valueStyle={STATISTICS_STYLE}
            />
          </Col>
          <Col>
            <StatisticErrorIndex
              title="Error Index"
              pullRequests={data.projects.flatMap(
                project => project.pullRequests
              )}
              placement="bottom"
              popoverContent={
                <Suspense fallback={<Loading />}>
                  <StatisticErrorIndexByProject projects={data.projects} />
                </Suspense>
              }
            />
          </Col>
          <Col>
            <Suspense fallback={<Loading size={16} />}>
              <StatisticDate
                date={
                  data.metadata?.date
                    ? new Date(Date.parse(data.metadata?.date))
                    : new Date()
                }
                text="Creation Date"
                intervalSeconds={1}
              />
            </Suspense>
          </Col>
          <Col>
            <Suspense fallback={<Loading size={16} />}>
              <StatisticDate
                date={latestLoad}
                text="Latest Load"
                intervalSeconds={1}
              />
            </Suspense>
          </Col>
        </Row>
      </PageHeader>
    </Card>
  );
};

export default CurrentStatusHeader;
