import {
  InfoCircleOutlined,
  NodeCollapseOutlined,
  ReloadOutlined,
  LinkOutlined
} from "@ant-design/icons";
import {
  Button,
  Card,
  Col,
  Modal,
  PageHeader,
  Popover,
  Row,
  Skeleton,
  Statistic,
  Typography,
  Tooltip
} from "antd";
import React, { Suspense } from "react";
import { IData } from "../../model/data.model";
import { STATISTICS_STYLE } from "../../shared/constants";
import Loading from "../shared/Loading";
import StatisticDate from "../shared/StatisticDate";
import StatisticErrorIndex from "../shared/StatisticErrorIndex";
const ProjectStatusInformation = React.lazy(
  () => import("../shared/ProjectStatusInformation")
);
const StatisticPullRequests = React.lazy(
  () => import("../shared/StatisticPullRequests")
);
const StatisticErrorIndexByProject = React.lazy(
  () => import("../shared/StatisticErrorIndexByProject")
);

interface ICurrentStatusHeader {
  data: IData;
  activePanels?: string[];
  loading: boolean;
  reload: () => void;
  latestLoad: Date;
}
export const CurrentStatusHeader: React.FC<ICurrentStatusHeader> = props => {
  const infoModal = () =>
    Modal.info({
      content: (
        <Suspense fallback={<Skeleton />}>
          <ProjectStatusInformation />
        </Suspense>
      ),
      onOk() {},
      width: 1000,
      centered: true
    });
  return (
    <Card style={{ margin: 24, marginTop: 10 }}>
      <PageHeader
        title={<Typography.Title level={2}>Project Status</Typography.Title>}
        subTitle="List of pull requests"
        style={{ padding: 0 }}
        extra={[
          <Tooltip key="reaload" title="Reload information from service">
            <Button
              key="reload"
              type="primary"
              icon={<ReloadOutlined />}
              loading={props.loading}
              onClick={props.reload}
            >
              Reload
            </Button>
          </Tooltip>,
          <Tooltip key="info" title="Show project status information">
            <Button
              key="info"
              type="text"
              shape="circle"
              icon={<InfoCircleOutlined />}
              onClick={infoModal}
            />
          </Tooltip>
        ]}
      >
        <Row gutter={16}>
          <Col>
            <Statistic
              title="Generated By"
              value={props.data?.metadata?.createdBy}
              valueStyle={STATISTICS_STYLE}
              suffix={
                props.data?.metadata?.createdUrl ? (
                  <Tooltip title="Visit job generating the report">
                    <Button
                      type="link"
                      href={props.data?.metadata?.createdUrl}
                      target="_blank"
                      icon={<LinkOutlined />}
                      style={{
                        padding: 0,
                        ...STATISTICS_STYLE,
                        fontWeight: "bold"
                      }}
                    />
                  </Tooltip>
                ) : null
              }
            />
          </Col>
          <Col>
            <Popover
              content={
                <Suspense fallback={<Loading />}>
                  <StatisticPullRequests projects={props.data.data} size={12} />
                </Suspense>
              }
              placement="bottom"
            >
              <Statistic
                title="Number of Projects"
                prefix={<NodeCollapseOutlined />}
                value={props.data.data.length}
                valueStyle={STATISTICS_STYLE}
              />
            </Popover>
          </Col>
          <Col>
            <StatisticErrorIndex
              title="Error Index"
              pullRequests={props.data.data.flatMap(
                project => project.pullRequests
              )}
              placement="bottom"
              popoverContent={
                <Suspense fallback={<Loading />}>
                  <StatisticErrorIndexByProject projects={props.data.data} />
                </Suspense>
              }
            />
          </Col>
          <Col>
            <Suspense fallback={<Loading size={16} />}>
              <StatisticDate
                date={
                  props.data?.metadata?.date
                    ? new Date(Date.parse(props.data?.metadata?.date))
                    : new Date()
                }
                text="Creation Date"
                intervalSeconds={1}
              />
            </Suspense>
          </Col>
          <Col>
            <Suspense fallback={<Loading size={16} />}>
              <StatisticDate
                date={props.latestLoad}
                text="Latest Load"
                intervalSeconds={1}
              />
            </Suspense>
          </Col>
        </Row>
      </PageHeader>
    </Card>
  );
};

export default CurrentStatusHeader;
