name: Publish Action

on:
  push:
    branches:
      - main
    paths:
      - "packages/action/package.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn publish --access public
        working-directory: packages/action/      
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
